site_name: manymore13
site_url: https://manymore13.github.io/
site_dir: docs
docs_dir: posts
use_directory_urls: false
copyright: Copyright © 2023 
site_description: blog
site_author : manymore13
theme:
  name: material
nav:
    - 技术: 技术分享.md
    - 金融: 金融分享.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
