name: Deploy static content to Pages
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: git pull    
      - run: pip install -r requirements.txt
      - run: cd pelican-themes
      - run: pelican-themes -i bootstrap
      - run: cd ..
      - run: pelican posts -o output -s pelicanconf.py
      - run: ghp-import output -b gh-pages
      - run: git push origin gh-pages
