name: update notes

on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: exe main.sh
      run: |
        chmod +x main.sh
        ./main.sh
    
        
          
    
