name: update notes

on:
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  update_notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Execute update_notes.sh
      run: |
        chmod +x update_notes.sh
        ./update_notes.sh

